### ISSUE TITLE
pip install on v0.13 does not include r subdirectory 

### ISSUE THREAD

**Issue by Arvinds-ds** [edwardlib/observations#26]
The r subfolder does not get installed in `site-packages`

**Comment by dustinvtran** [comment]
Silly mistake. All submodules should be written to be imported inside `setup.py`, similar to [Edward's](https://github.com/blei-lab/edward/blob/master/setup.py). Contribution welcome.

**Comment by dustinvtran** [comment]
Fixed in #27.
